# Generated by Django 4.0.4 on 2022-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('num_equipo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_quipo', models.CharField(max_length=100)),
                ('tipo_equipo', models.CharField(blank=True, max_length=100)),
                ('modelo_equipo', models.CharField(max_length=100)),
                ('marca_equipo', models.CharField(max_length=100)),
            ],
        ),
    ]
