# Generated by Django 4.0.4 on 2022-05-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_supervisores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabajadore',
            new_name='Supervisore',
        ),
    ]
