# Generated by Django 4.0.4 on 2022-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadore',
            fields=[
                ('rut_trabajador', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres_trabajador', models.CharField(max_length=100)),
                ('apellidos_trabajador', models.CharField(max_length=100)),
                ('fecha_nac_trabajador', models.DateField()),
                ('telefono_trabajador', models.IntegerField()),
                ('email_trabajador', models.EmailField(max_length=254)),
            ],
        ),
    ]
