# Generated by Django 4.0.4 on 2022-05-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gestion_equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia_Mantenimiento',
            fields=[
                ('folio_h_m', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_trabajador', models.CharField(max_length=200)),
                ('dia_turno', models.CharField(max_length=10)),
                ('fecha_mantencion', models.DateField()),
                ('rut_trabajador', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=10)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hojas_mantencione',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_intervencion', models.IntegerField()),
                ('descripcion_trabajo', models.TextField(max_length=300)),
                ('ot', models.CharField(max_length=20)),
                ('horometro', models.IntegerField()),
                ('folio_mantencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_hoja_mantecion.asistencia_mantenimiento')),
                ('numero_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_equipo.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia_mantenimiento',
            name='equipo',
            field=models.ManyToManyField(through='Gestion_hoja_mantecion.Hojas_mantencione', to='Gestion_equipo.equipo'),
        ),
    ]
